"""Add collection models

Revision ID: 1dc5f8677cbc
Revises: e3c2a7d9b123
Create Date: 2025-12-30 07:25:51.723825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc5f8677cbc'
down_revision = 'e3c2a7d9b123'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_lists',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_lists_user_id'), 'reading_lists', ['user_id'], unique=False)
    op.create_index(op.f('ix_reading_lists_uuid'), 'reading_lists', ['uuid'], unique=True)
    op.create_table('highlights',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('position_start', sa.Integer(), nullable=True),
    sa.Column('position_end', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_highlights_post_id'), 'highlights', ['post_id'], unique=False)
    op.create_index(op.f('ix_highlights_user_id'), 'highlights', ['user_id'], unique=False)
    op.create_index(op.f('ix_highlights_uuid'), 'highlights', ['uuid'], unique=True)
    op.create_table('reading_history',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('read_progress', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_history_post_id'), 'reading_history', ['post_id'], unique=False)
    op.create_index(op.f('ix_reading_history_user_id'), 'reading_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_reading_history_uuid'), 'reading_history', ['uuid'], unique=True)
    op.create_table('reading_list_items',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['reading_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_list_items_list_id'), 'reading_list_items', ['list_id'], unique=False)
    op.create_index(op.f('ix_reading_list_items_post_id'), 'reading_list_items', ['post_id'], unique=False)
    op.create_index(op.f('ix_reading_list_items_uuid'), 'reading_list_items', ['uuid'], unique=True)
    op.drop_index(op.f('ix_user_role_changes_created_at'), table_name='user_role_changes')
    op.drop_constraint(op.f('user_role_changes_changed_by_id_fkey'), 'user_role_changes', type_='foreignkey')
    op.drop_constraint(op.f('user_role_changes_user_id_fkey'), 'user_role_changes', type_='foreignkey')
    op.create_foreign_key(None, 'user_role_changes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_role_changes', 'users', ['changed_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_role_changes', type_='foreignkey')
    op.drop_constraint(None, 'user_role_changes', type_='foreignkey')
    op.create_foreign_key(op.f('user_role_changes_user_id_fkey'), 'user_role_changes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('user_role_changes_changed_by_id_fkey'), 'user_role_changes', 'users', ['changed_by_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_user_role_changes_created_at'), 'user_role_changes', ['created_at'], unique=False)
    op.drop_index(op.f('ix_reading_list_items_uuid'), table_name='reading_list_items')
    op.drop_index(op.f('ix_reading_list_items_post_id'), table_name='reading_list_items')
    op.drop_index(op.f('ix_reading_list_items_list_id'), table_name='reading_list_items')
    op.drop_table('reading_list_items')
    op.drop_index(op.f('ix_reading_history_uuid'), table_name='reading_history')
    op.drop_index(op.f('ix_reading_history_user_id'), table_name='reading_history')
    op.drop_index(op.f('ix_reading_history_post_id'), table_name='reading_history')
    op.drop_table('reading_history')
    op.drop_index(op.f('ix_highlights_uuid'), table_name='highlights')
    op.drop_index(op.f('ix_highlights_user_id'), table_name='highlights')
    op.drop_index(op.f('ix_highlights_post_id'), table_name='highlights')
    op.drop_table('highlights')
    op.drop_index(op.f('ix_reading_lists_uuid'), table_name='reading_lists')
    op.drop_index(op.f('ix_reading_lists_user_id'), table_name='reading_lists')
    op.drop_table('reading_lists')
    # ### end Alembic commands ### 