"""adding review fields

Revision ID: 3761dc7be39d
Revises: 6a7fae79dbce
Create Date: 2025-08-21 15:43:18.976010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3761dc7be39d'
down_revision = '6a7fae79dbce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_reviewed', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('posts', sa.Column('review_comments', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('is_flagged', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('posts', sa.Column('reviewed_at', sa.DateTime(), nullable=True))

        # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'reviewed_at')
    op.drop_column('posts', 'is_flagged')
    op.drop_column('posts', 'review_comments')
    op.drop_column('posts', 'is_reviewed')
    # ### end Alembic commands ### 