"""Add parent_id to categories

Revision ID: 4210f21b0a6b
Revises: d5ea00a97b18
Create Date: 2025-08-03 21:42:22.781435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4210f21b0a6b'
down_revision = 'd5ea00a97b18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # Drop the foreign key and parent_id column
    op.drop_constraint('fk_categories_parent_id', 'categories', type_='foreignkey')
    op.drop_column('categories', 'parent_id')