"""add_ai_drafts_and_generation_logs

Revision ID: 51994986c29a
Revises: 110385da100f
Create Date: 2025-10-31 02:05:23.433819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51994986c29a'
down_revision = '110385da100f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_drafts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=True),
    sa.Column('model_used', sa.Enum('GROK', 'OPENAI', 'GEMINI', name='aimodel'), nullable=True),
    sa.Column('favorite', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_drafts_user_id'), 'ai_drafts', ['user_id'], unique=False)
    op.create_index(op.f('ix_ai_drafts_uuid'), 'ai_drafts', ['uuid'], unique=True)
    op.create_table('ai_generation_logs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=True),
    sa.Column('model_used', sa.Enum('GROK', 'OPENAI', 'GEMINI', name='aimodel'), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('generation_time', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_generation_logs_user_id'), 'ai_generation_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_ai_generation_logs_uuid'), 'ai_generation_logs', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_generation_logs_uuid'), table_name='ai_generation_logs')
    op.drop_index(op.f('ix_ai_generation_logs_user_id'), table_name='ai_generation_logs')
    op.drop_table('ai_generation_logs')
    op.drop_index(op.f('ix_ai_drafts_uuid'), table_name='ai_drafts')
    op.drop_index(op.f('ix_ai_drafts_user_id'), table_name='ai_drafts')
    op.drop_table('ai_drafts')
    # ### end Alembic commands ### 