"""add provider column to users

Revision ID: 6a7fae79dbce
Revises: 284a182ead1d
Create Date: 2025-08-18 12:26:18.386519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a7fae79dbce'
down_revision = '284a182ead1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('users', sa.Column('provider', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'provider')
    # ### end Alembic commands ### 