"""Update profile social links fields

Revision ID: 932b4f186e7d
Revises: 1dc5f8677cbc
Create Date: 2025-12-30 20:51:24.055023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932b4f186e7d'
down_revision = '1dc5f8677cbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('instagram_handle', sa.String(length=100), nullable=True))
    op.add_column('profiles', sa.Column('facebook_handle', sa.String(length=100), nullable=True))
    op.alter_column('profiles', 'twitter_handle',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('profiles', 'linkedin_handle',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_column('profiles', 'website')
    op.drop_column('profiles', 'github_handle')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('github_handle', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('website', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.alter_column('profiles', 'linkedin_handle',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('profiles', 'twitter_handle',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('profiles', 'facebook_handle')
    op.drop_column('profiles', 'instagram_handle')
    # ### end Alembic commands ### 