"""is_approved in Comment to false

Revision ID: 94dad6fa8be8
Revises: f288e23a929a
Create Date: 2025-07-22 16:48:13.747513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94dad6fa8be8'
down_revision = 'f288e23a929a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 