"""editing comment updated and created at fields

Revision ID: a8258ff121a6
Revises: 6f165d214207
Create Date: 2025-07-22 14:58:01.816390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8258ff121a6'
down_revision = '6f165d214207'
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()

    if bind.dialect.name == "sqlite":
        with op.batch_alter_table('comments') as batch_op:
            batch_op.alter_column(
                'created_at',
                existing_type=sa.DateTime(),
                nullable=False
            )
            batch_op.alter_column(
                'updated_at',
                existing_type=sa.DateTime(),
                nullable=True
            )
    else:
        op.alter_column(
            'comments',
            'created_at',
            existing_type=sa.TIMESTAMP(timezone=True),
            type_=sa.DateTime(timezone=True),
            nullable=False,
            existing_server_default=sa.text('now()')
        )
        op.alter_column(
            'comments',
            'updated_at',
            existing_type=sa.TIMESTAMP(timezone=True),
            type_=sa.DateTime(timezone=True),
            existing_nullable=True
        )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('comments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ### 