"""Add soft delete to posts

Revision ID: df1cd9bb56b1
Revises: 46f2c44eb54a
Create Date: 2025-07-18 00:08:59.671354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df1cd9bb56b1'
down_revision: Union[str, Sequence[str], None] = '46f2c44eb54a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'deleted_at')
    # ### end Alembic commands ###
